# `FROM node:alpine` is breaking the code in our server/index.js.
FROM node:14.14.0-alpine

USER node
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

# using nodemon for development
CMD ["npm", "run", "dev"]