FROM node:alpine

USER node
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

# using nodemon for development
CMD ["npm", "run", "dev"]